Vagrant.configure("2") do |config|
  config.vm.box = "johnpbloch/trusty64"
  config.vm.box_check_update = false
  config.vm.synced_folder "shared/", "/shared", create: true
  config.vm.synced_folder "dataset/", "/dataset", create: true

  config.vm.define "mongod-m036" do |server|
    server.vm.provider "hyperv" do |vb|
       vb.vmname = "mongod-m036"
	   vb.cpus = 2
       vb.memory = 2048
    end
    server.vm.hostname = "m036.mongodb.university"
    server.vm.network :private_network, ip: "192.168.36.100"
    server.vm.provision :shell, path: "provision-mongod", args: ENV['ARGS']
  end
end
